Models/Catagory.cs
namespace UniqloProject.Models
{
    public class Catagory
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsDelete { get; set; }

        public ICollection<Product> Products { get; set; }

    }
}

Models/Product.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace UniqloProject.Models;

public class Product
{
    public int Id { get; set; }

    public string Title { get; set; }
    public string ImgUrl { get; set; }
    public int Price { get; set; }
    public int NewPrice { get; set; }
    public bool IsDelete { get; set; }

    public int CatagoryId { get; set; }
    [NotMapped]
    public Catagory Catagory { get; set; }
}

Models/SliderItem.cs
namespace UniqloProject.Models;

public class SliderItem
{
    public int Id { get; set; }
    public string ImgPath { get; set; }
    public string ButtonUrl { get; set; }
    public string Title { get; set; }
}

ViewModels/CatagoryVM.cs
using UniqloProject.Models;

namespace UniqloProject.ViewModels;

public class CatagoryVM
{
    public string Name { get; set; }
}

ViewModels/ProductVM.cs
using System.ComponentModel.DataAnnotations.Schema;
using UniqloProject.Models;

namespace UniqloProject.ViewModels;

public class ProductVM
{
   

    public string Title { get; set; }
    public string ImgUrl { get; set; }
    public int Price { get; set; }
    public int NewPrice { get; set; }
    public int CatagoryId { get; set; }
   
}

Areas/Admin/Controllers/CatagoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using UniqloProject.DAL;
using UniqloProject.Models;
using UniqloProject.ViewModels;

namespace UniqloProject.Areas.Admin.Controllers;
[Area("Admin")]
public class CatagoryController : Controller
{
    private readonly AppDbContext _context;

    public CatagoryController(AppDbContext context)
    {
        _context = context;
    }

    public IActionResult Index()
    {
        List<Catagory> catagories = _context.Catagories.ToList();
        return View(catagories);

    }
    public IActionResult Delete(int Id)
    {
        Catagory? catagory = _context.Catagories.Find(Id);
        if (catagory == null)
        {
            return NotFound("bele product yoxdur");
        }
        catagory.IsDelete = true;
        _context.SaveChanges();
        return RedirectToAction(nameof(Index));

    }
    public IActionResult Create()
    {
        return View();
    }
    [HttpPost]
    public IActionResult Create(CatagoryVM catagoryVM)
    {
        if (ModelState.IsValid)
        {
            Catagory catagory = new Catagory()
            {
                Name = catagoryVM.Name,
            };
            _context.Catagories.Add(catagory);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));

        }

        return View(catagoryVM);
    }

    public IActionResult Update(int Id)
    {
        Catagory? catagory = _context.Catagories.Find(Id);
        if (catagory == null)
        {
            return NotFound("bele deyer tapilmadu");
        }
        //CatagoryVM catagoryVM = new CatagoryVM()
        //{
        //    Name= catagory.Name
        //};
        return View(catagory);
    } 
    [HttpPost]
    public IActionResult Update(Catagory catagory)
    {
        Catagory? updateCatagory = _context.Catagories.AsNoTracking().FirstOrDefault(x => x.Id == catagory.Id);
        if (updateCatagory == null)
        {
            return NotFound("No Such Service");
        }
        _context.Catagories.Update(catagory);
        _context.SaveChanges();
        return RedirectToAction(nameof(Index));
    }

}

Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using UniqloProject.DAL;
using UniqloProject.Models;

namespace UniqloProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        private readonly AppDbContext _context;
        public HomeController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            List<SliderItem> sliderItems = _context.SliderItems.ToList();
            return View(sliderItems);
        }

        public IActionResult Delete(int Id)
        {
            SliderItem? deleteourWork = _context.SliderItems.Find(Id);
            if (deleteourWork == null)
            {
                return NotFound("NO such Works");
            }


            _context.SliderItems.Remove(deleteourWork);
            _context.SaveChanges();


            return RedirectToAction(nameof(Index));
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(SliderItem sliderItem)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest("smth went wrong");
            }
            else
            {
                _context.SliderItems.Add(sliderItem);
                _context.SaveChanges();
            }


            return RedirectToAction(nameof(Index));
        }



    }
}

Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UniqloProject.DAL;
using UniqloProject.Models;
using UniqloProject.ViewModels;

namespace UniqloProject.Areas.Admin.Controllers;
[Area("Admin")]
public class ProductController : Controller
{
    private AppDbContext _context;

    public ProductController(AppDbContext context)
    {
        _context = context;
    }

    public IActionResult Index()
    {
        List<Product> products = _context.Products.ToList();
        return View(products);
    }
    public IActionResult Delete(int Id)
    {
        Product? product = _context.Products.Find(Id);
        if (product == null)
        {
            return NotFound("bele product yoxdur");
        }
        product.IsDelete = true;
        _context.SaveChanges();
        return RedirectToAction(nameof(Index));
    }
    public IActionResult Create()
    {
        ViewBag.Catagories = new SelectList(_context.Catagories, "Id", "Name");

        return View();
    }
    [HttpPost]
    public IActionResult Create(ProductVM productVM)
    {
        if (ModelState.IsValid)
        {
            Product product = new Product()
            {
                Title = productVM.Title,
                ImgUrl = productVM.ImgUrl,
                Price = productVM.Price,
                NewPrice = productVM.NewPrice,
                CatagoryId = productVM.CatagoryId,
            };
            _context.Products.Add(product);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        ViewBag.Catagories = new SelectList(_context.Catagories, "Id", "Name");
        return View(productVM);
    }
 
    public IActionResult Update(int Id)
    {
       Product? product = _context.Products.Find(Id);
        if (product == null)
        {
            return NotFound("Bu id ye uygunun tapilmafdi");
        }
        ProductVM productVM = new ProductVM()
        {
            Title= product.Title,
            ImgUrl = product.ImgUrl,
            Price = product.Price,
            NewPrice = product.NewPrice,
            CatagoryId = product.CatagoryId


        };
        ViewBag.Catagories = new SelectList(_context.Catagories, "Id", "Name");
        return View(productVM);
    }
    [HttpPost]
    public IActionResult Update(int id, ProductVM productVM)
    {
       Product? updateProduct = _context.Products.AsNoTracking().FirstOrDefault(x => x.Id == id);
        if (updateProduct == null)
        {
            return NotFound("tapilmadi");
        }
        Product product = new Product()
        {
            Id= id,
            Title= productVM.Title,
            ImgUrl= productVM.ImgUrl,
            Price = productVM.Price,
            NewPrice = productVM.NewPrice,
            CatagoryId = productVM.CatagoryId
        };
        ViewBag.Catagories = new SelectList(_context.Catagories, "Id", "Name");
        _context.Products.Update(product);
        _context.SaveChanges();
        return RedirectToAction(nameof(Index),"Home");
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using UniqloProject.DAL;
using UniqloProject.Models;

namespace UniqloProject.Controllers
{
    public class HomeController : Controller
    {
      private readonly  AppDbContext _context;
        public HomeController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
           List<SliderItem> sliderItems = _context.SliderItems.ToList();
            return View(sliderItems);
        }
    }
}

Areas/Admin/Views/Catagory/Create.cshtml
@using UniqloProject.Models;
@using UniqloProject.ViewModels;

@model CatagoryVM;


@{
    ViewData["Title"] = "Create";
}



<div class="row ml-3">
    <h1>Create</h1>
    <br />
    <h4>Catagory</h4>
    <br />
    <div class="col-md-12">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">

                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    </div>
    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>

Areas/Admin/Views/Catagory/Index.cshtml
@using UniqloProject.Models;
@model List<Catagory>

<div class="container-fluid">


    <h1 class="h3 mb-2 text-gray-800">Tables</h1>
    <p class="mb-4">
        DataTables is a third party plugin that is used to generate the demo table below.
        For more information about DataTables, please visit the <a target="_blank"
                                                                   href="https://datatables.net">official DataTables documentation</a>.
    </p>


    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">


                <a asp-area="Admin" asp-controller="Catagory" asp-action="Create" class="btn btn-success">Create</a>

                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>IsDelete</th>
                            <th>Update</th>
                            <th>Delete</th>


                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>IsDelete</th>

                            <th>Update</th>
                            <th>Delete</th>
                           

                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach (Catagory item in Model)
                        {
                           

                            <tr>
                                <td>@item.Id</td>
                                <td>@item.Name</td>
                                <td>@item.IsDelete</td>

                                <th><a asp-area="Admin" asp-controller="Catagory" asp-action="Update" asp-route-id="@item.Id" class="btn btn-success" >Update</a></th>
                                <th><a asp-area="Admin" asp-controller="Catagory" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a></th>
                            </tr>
                            
                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>

Areas/Admin/Views/Catagory/Update.cshtml
@using UniqloProject.Models;
@using UniqloProject.ViewModels;

@model Catagory;


@{
    ViewData["Title"] = "Update";
}



<div class="row ml-3">
    <h1>Create</h1>
    <br />
    <h4>Catagory</h4>
    <br />
    <div class="col-md-12">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">

                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>


            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    </div>
    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>

Areas/Admin/Views/Home/Index.cshtml
@using UniqloProject.Models;
@model List<SliderItem>



<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Tables</h1>
    <p class="mb-4">
        DataTables is a third party plugin that is used to generate the demo table below.
        For more information about DataTables, please visit the <a target="_blank"
                                                                   href="https://datatables.net">official DataTables documentation</a>.
    </p>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">

                   @foreach(SliderItem item in Model)
                        {
                <a asp-controller="Create" asp-action="Index" asp-route-id="@item.Id" class="btn btn-success" >Create</a>

                        }
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                   
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>ImgPath</th>
                            <th>ButtonUrl</th>
                            <th>Title</th>
                            <th>Update</th>
                            <th>Delete</th>



                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>#</th>
                            <th>ImgPath</th>
                            <th>ButtonUrl</th>
                            <th>Title</th>
                            <th>Update</th>
                            <th>Delete</th>



                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach(SliderItem item in Model)
                        {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.ImgPath</td>
                                <td>@item.ButtonUrl</td>
                                <td>@item.Title</td>
                                <th><a class="btn btn-success" href="#">Update</a></th>
                                <th><a  class="btn btn-danger">Delete</a></th>
                            </tr>
                       
                        }
                        
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->

Areas/Admin/Views/Home/create.cshtml
@using UniqloProject.Models;

@model SliderItem
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ButtonUrl" class="control-label"></label>
                <input asp-for="ButtonUrl" class="form-control" />
                <span asp-validation-for="ButtonUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImgPath" class="control-label"></label>
                <input asp-for="ImgPath" class="form-control" />
                <span asp-validation-for="ImgPath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            

            

            <div class="form-group">
                <button type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Areas/Admin/Views/Product/Create.cshtml
@using UniqloProject.Models;
@using UniqloProject.ViewModels;

@model ProductVM;


 @{
    ViewData["Title"] = "Create";
}



<div class="row ml-3">
    <h1>Create</h1>
    <br />
    <h4>Product</h4>
    <br />
    <div class="col-md-12">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">

                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NewPrice" class="control-label"></label>
                <input asp-for="NewPrice" class="form-control" />
                <span asp-validation-for="NewPrice" class="text-danger"></span>
            </div>

            


            <div class="form-group">
                <label asp-for="CatagoryId" class="control-label"></label>
                <select asp-for="CatagoryId" class="form-control" asp-items="ViewBag.Catagories">
                    <option hidden value="">-- Select Service --</option>
                </select>
                <span asp-validation-for="CatagoryId" class="text-danger"></span>
            </div>

            <div class="form-group">

                <label asp-for="ImgUrl" class="control-label"></label>
                <input asp-for="ImgUrl" class="form-control" />
                <span asp-validation-for="ImgUrl" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    </div>
    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>

Areas/Admin/Views/Product/Index.cshtml
@using UniqloProject.Models;
@model List<Product>
<div class="container-fluid">


    <h1 class="h3 mb-2 text-gray-800">Tables</h1>
    <p class="mb-4">
        DataTables is a third party plugin that is used to generate the demo table below.
        For more information about DataTables, please visit the <a target="_blank"
                                                                   href="https://datatables.net">official DataTables documentation</a>.
    </p>


    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">

             
                    <a asp-area="Admin" asp-controller="Product" asp-action="Create"  class="btn btn-success">Create</a>

                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Title</th>
                            <th>ImgUrl</th>
                            <th>Price</th>
                            <th>NewPrice</th>
                            <th>CatagoryId</th>
                            <th>IsDelete</th>
                            <th>Update</th>
                            <th>Delete</th>

                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>#</th>
                            <th>Title</th>
                            <th>ImgUrl</th>
                            <th>Price</th>
                            <th>NewPrice</th>
                            <th>CatagoryId</th>
                            <th>IsDelete</th>
                            <th>Update</th>
                            <th>Delete</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach (Product item in Model)
                        {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.Title</td>
                                <td>@item.ImgUrl</td>
                                <td>@item.Price</td>
                                <td>@item.NewPrice</td>
                                <td>@item.CatagoryId</td>
                                <td>@item.IsDelete</td>


                                <th><a asp-area="Admin" asp-controller="Product" asp-action="Update" asp-route-id="@item.Id" class="btn btn-success" >Update</a></th>
                                <th><a asp-area="Admin" asp-controller="Product" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a></th>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>

Areas/Admin/Views/Product/Update.cshtml
@using UniqloProject.Models;
@using UniqloProject.ViewModels;

@model ProductVM;

<div class="row ml-3">
    <h1>Create</h1>
    <br />
    <h4>Product</h4>
    <br />
    <div class="col-md-12">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">

                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NewPrice" class="control-label"></label>
                <input asp-for="NewPrice" class="form-control" />
                <span asp-validation-for="NewPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CatagoryId" class="control-label"></label>
                <select asp-for="CatagoryId" class="form-control" asp-items="ViewBag.Catagories">
                    <option hidden value="">-- Select Service --</option>
                </select>
                <span asp-validation-for="CatagoryId" class="text-danger"></span>
            </div>

            <div class="form-group">

                <label asp-for="ImgUrl" class="control-label"></label>
                <input asp-for="ImgUrl" class="form-control" />
                <span asp-validation-for="ImgUrl" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" class="btn btn-primary" />
            </div>
        </form>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    </div>
    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>